language: node_js

node_js:
  - "12.16.1"

cache: npm

script:
  - npm test

before_deploy: 
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: netlify
  site: $NETLIFY_SITE_ID
  edge: true
  auth: $AUTH
  # script: netlify deploy --dir=dist --prod
  on: 
    branch: main
